///////////////////////////////////////////////////////////
//  CLIENTE.cs
//  Implementation of the Class CLIENTE
//  Generated by Enterprise Architect
//  Created on:      30-nov.-2023 12:07:30
//  Original author: USUARIO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CLIENTE {

	public int Celular;
	public int Ci;
	public string Nombre;
	public PAGO m_PAGO;

	public .CLIENTE(){

	}

	~CLIENTE(){

	}

}//end CLIENTE