///////////////////////////////////////////////////////////
//  PAGO.cs
//  Implementation of the Class PAGO
//  Generated by Enterprise Architect
//  Created on:      30-nov.-2023 12:07:30
//  Original author: USUARIO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PAGO {

	public DateTime Fecha;
	public decimal MontoTotal;
	public int NumeroRecibo;
	public GUITARRA m_GUITARRA;

	public PAGO(){

	}

	~PAGO(){

	}

}//end PAGO