///////////////////////////////////////////////////////////
//  USUARIO.cs
//  Implementation of the Class USUARIO
//  Generated by Enterprise Architect
//  Created on:      30-nov.-2023 12:07:30
//  Original author: USUARIO
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class USUARIO {

	public string Cuenta;
	public string Nombre;
	public string Password;
	public string Rol = Cajera,Gerente;
	public PAGO m_PAGO;

	public USUARIO(){

	}

	~USUARIO(){

	}

}//end USUARIO